{
 "title": "Adoption Dashboard v5",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Transaction Trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Transaction by Method",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"context_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "# Transaction by Type",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"type_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Top 10 - Transaction Delay",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction_of_duration1\")\n  |> group(columns: [\"_start\", \"_stop\"])\n  |> unique()\n  |> top(n:10, columns: [\"_value\"])\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "# Devices by Method",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"context_dev_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "# Devices by Transaction Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"type_dev_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "# Services by Method",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"context_serv_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "# Services by Transaction type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"type_serv_count1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  { "title": "Services Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Services Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Priority Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Timeline Services Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "P1 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P2 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p2\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P3 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p3\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P4 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p4\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P5 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Devices by priority", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "P1 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P2 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p2\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P3 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p3\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P4 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p4\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P5 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IOS-XR Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] == \"cisco-iosxr-cli-7.33\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IOS Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] == \"cisco-ios-cli-6.74\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Other Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] != \"cisco-ios-cli-6.74\" and r[\"ned\"] != \"cisco-iosxr-cli-7.33\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Changes Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Total Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"changes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"qty\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Changes Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 87 },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"changes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"qty\")\r\n  |> group(columns: [\"change\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  { "title": "Licenses Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Network Elements",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Licensing Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Data Recorded at:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}